name: PullRequest

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test